/**
 * `08` §12.12 obligation 6 — the PINNED advisory-lock vectors.
 *
 * Normative sources: D-072, *Ugovor advisory locka*; D-079 `OD-P5-I4C-3`; `08` §12.12 obligation
 * 6, as refined by the `Preciziranje obaveze 6` annotation; `09` §4.2.
 *
 * ANTI-TAUTOLOGY — HOW THE EXPECTED VALUES WERE PRODUCED
 *
 * NOT ONE expected value below was generated by the implementation under test, and none was
 * produced by any JavaScript at all. Each preimage was assembled BY HAND from the specification —
 * `LP32(X) = uint32_be(length(UTF8(X))) || UTF8(X)`, in the frozen component order — using
 * `printf` and `xxd` to render UTF-8 bytes and `printf '%08x'` to render the four-byte
 * big-endian length prefixes. Each digest was then computed OUTSIDE the workspace with GNU
 * coreutils `sha256sum` over the raw bytes (`xxd -r -p | sha256sum`), and each `int64` was
 * produced by the shell's own 64-bit two's-complement arithmetic (`$((16#<first 8 bytes>))`),
 * never by `readBigInt64BE`. The same discipline `P5-I4B` applied to its RFC 8785 vectors.
 *
 * A vector that had been generated by calling `advisoryLockKey` would assert only that the
 * function is deterministic, which is not what `08` §12.12 obligation 6 asks for.
 *
 * WHAT THE FIVE VECTORS PROVE, TAKEN TOGETHER
 *
 *  1. the canonical production scope, and a POSITIVE signed `int64`;
 *  2. the same scope with a different key, and a NEGATIVE signed `int64` — so the sign bit is
 *     genuinely carried through rather than masked away;
 *  3 + 4. COMPONENT-BOUNDARY AMBIGUITY RESISTANCE: `("ab","c")` and `("a","bc")` flatten to the
 *     same `abcde` under plain or delimiter concatenation, and MUST produce different locks;
 *  5. UTF-8 BYTE counting: a value whose byte length, UTF-16 code-unit length and code-point
 *     length are all different (7, 4 and 3) pins the prefix to the BYTE count.
 */

import { describe, expect, it } from 'vitest';

import { IDEMPOTENCY_ENDPOINT_POST_PATIENT_REFERENCES } from '../idempotency.constants.js';
import {
  ADVISORY_LOCK_DOMAIN_TAG,
  ADVISORY_LOCK_KEY_BYTES,
  ADVISORY_LOCK_LENGTH_PREFIX_BYTES,
  advisoryLockKey,
  advisoryLockPreimage,
} from './advisory-lock-key.js';

/** The canonical fixture scope. Obviously synthetic, non-PHI values (`09` §9). */
const PRACTICE = '11111111-1111-4111-8111-111111111001';
const USER = '22222222-2222-4222-8222-222222222001';

/**
 * One specification-derived vector.
 *
 * `preimage` is the complete hex of `LP32(tag) || LP32(practice) || LP32(user) || LP32(endpoint)
 * || LP32(key)`; `digest` is its SHA-256; `lockKey` is the first eight digest bytes read as a
 * big-endian signed `int64`.
 */
interface Vector {
  readonly name: string;
  readonly practiceId: string;
  readonly userId: string;
  readonly endpoint: string;
  readonly idempotencyKey: string;
  readonly preimage: string;
  readonly digest: string;
  readonly lockKey: bigint;
}

const VECTORS: readonly Vector[] = [
  {
    name: 'canonical scope, positive int64',
    practiceId: PRACTICE,
    userId: USER,
    endpoint: IDEMPOTENCY_ENDPOINT_POST_PATIENT_REFERENCES,
    idempotencyKey: 'p5i4c-key-1',
    preimage:
      '0000000c6964656d2d6c6f636b2d76310000002431313131313131312d313131312d343131312d383131312d3131' +
      '313131313131313030310000002432323232323232322d323232322d343232322d383232322d3232323232323232' +
      '3230303100000018504f5354202f70617469656e742d7265666572656e6365730000000b70356934632d6b65792d31',
    digest: '60c7aeed2f9204abaca42a1331209fe9936c007aeade7b958a6d361903a30825',
    lockKey: 6973734881735083179n,
  },
  {
    name: 'canonical scope, NEGATIVE int64',
    practiceId: PRACTICE,
    userId: USER,
    endpoint: IDEMPOTENCY_ENDPOINT_POST_PATIENT_REFERENCES,
    idempotencyKey: 'p5i4c-key-2',
    preimage:
      '0000000c6964656d2d6c6f636b2d76310000002431313131313131312d313131312d343131312d383131312d3131' +
      '313131313131313030310000002432323232323232322d323232322d343232322d383232322d3232323232323232' +
      '3230303100000018504f5354202f70617469656e742d7265666572656e6365730000000b70356934632d6b65792d32',
    digest: 'b61448537c1f955b20f08b89a3bb461f2b4166d1a46bdadf1e4acaca0d3904fa',
    lockKey: -5326552935870524069n,
  },
  {
    name: 'boundary ambiguity A — user "ab", key "c"',
    practiceId: 'ab',
    userId: 'c',
    endpoint: 'd',
    idempotencyKey: 'e',
    preimage: '0000000c6964656d2d6c6f636b2d7631000000026162000000016300000001640000000165',
    digest: '6dca45bea9ae6e5c9fd7c587ef48f4332acd287c50af5c06ace2157d2521a7a2',
    lockKey: 7911212380622581340n,
  },
  {
    name: 'boundary ambiguity B — user "a", key "bc"',
    practiceId: 'a',
    userId: 'bc',
    endpoint: 'd',
    idempotencyKey: 'e',
    preimage: '0000000c6964656d2d6c6f636b2d7631000000016100000002626300000001640000000165',
    digest: 'f788195c92a5e64f73be7da0b457651980d523e47a55d292114e907ca733d554',
    lockKey: -610209864120670641n,
  },
  {
    name: 'multi-byte UTF-8 key — 7 bytes, 4 UTF-16 code units, 3 code points',
    practiceId: PRACTICE,
    userId: USER,
    endpoint: IDEMPOTENCY_ENDPOINT_POST_PATIENT_REFERENCES,
    // `e` + COMBINING ACUTE ACCENT + GRINNING FACE. Not an accepted `Idempotency-Key`
    // (`OD-P5-I4C-2` admits ASCII VCHAR only), and deliberately so: this vector pins the
    // ENCODING RULE of the derivation, which is defined over UTF-8 bytes for every component,
    // not the header domain. Production values are ASCII.
    idempotencyKey: 'é\u{1F600}',
    preimage:
      '0000000c6964656d2d6c6f636b2d76310000002431313131313131312d313131312d343131312d383131312d3131' +
      '313131313131313030310000002432323232323232322d323232322d343232322d383232322d3232323232323232' +
      '3230303100000018504f5354202f70617469656e742d7265666572656e6365730000000765cc81f09f9880',
    digest: 'd0e9b26e966baf33dcef8f357eab343d8c288f6113fef5967c124b58ea3c46eb',
    lockKey: -3392984656207171789n,
  },
];

/**
 * One vector by index, or a hard failure.
 *
 * A missing vector must break the suite loudly rather than silently skip an assertion: an
 * `undefined` here would turn a pinned-vector proof into a test that asserts nothing.
 */
function vectorAt(index: number): Vector {
  const vector = VECTORS[index];

  if (vector === undefined) {
    throw new Error(`The pinned vector table has no entry at index ${String(index)}.`);
  }

  return vector;
}

/** The scope object of one vector. */
function scopeOf(vector: Vector): Parameters<typeof advisoryLockPreimage>[0] {
  return {
    practiceId: vector.practiceId,
    userId: vector.userId,
    // The endpoint is a literal union in production; these vectors deliberately exercise other
    // component values too, so the cast states that this file tests the DERIVATION and not the
    // endpoint catalogue.
    endpoint: vector.endpoint as typeof IDEMPOTENCY_ENDPOINT_POST_PATIENT_REFERENCES,
    idempotencyKey: vector.idempotencyKey,
  };
}

describe('advisory lock key derivation (OD-P5-I4C-3, 08 §12.12 obligation 6)', () => {
  describe('the frozen constants', () => {
    it('pins the domain tag to the one authorised literal', () => {
      // Written out rather than compared to itself: an alternative tag is forbidden, and the
      // whole vector table below depends on this exact string.
      expect(ADVISORY_LOCK_DOMAIN_TAG).toBe('idem-lock-v1');
    });

    it('pins the length prefix to FOUR bytes and the key to EIGHT', () => {
      // An eight-byte length prefix is explicitly forbidden by `OD-P5-I4C-3`.
      expect(ADVISORY_LOCK_LENGTH_PREFIX_BYTES).toBe(4);
      expect(ADVISORY_LOCK_KEY_BYTES).toBe(8);
    });
  });

  describe.each(VECTORS)('vector: $name', (vector) => {
    it('produces the pinned preimage BYTES', () => {
      // The bytes, not merely the integer. A wrong component ORDER can still yield a plausible
      // digest; it cannot yield this hex string.
      expect(advisoryLockPreimage(scopeOf(vector)).toString('hex')).toBe(vector.preimage);
    });

    it('produces the pinned signed int64 lock key', () => {
      expect(advisoryLockKey(scopeOf(vector))).toBe(vector.lockKey);
    });
  });

  describe('what the pinned bytes prove about the encoding', () => {
    it('prefixes each component with its UTF-8 BYTE length, big-endian, in four bytes', () => {
      const preimage = advisoryLockPreimage(scopeOf(vectorAt(0)));

      // `idem-lock-v1` is 12 bytes, so the first four bytes are `00 00 00 0c` — big-endian. A
      // little-endian prefix would read `0c 00 00 00`, which this assertion excludes.
      expect(preimage.subarray(0, 4).toString('hex')).toBe('0000000c');
      expect(preimage.subarray(4, 16).toString('utf8')).toBe(ADVISORY_LOCK_DOMAIN_TAG);
    });

    it('counts BYTES, not UTF-16 code units and not code points', () => {
      const multiByte = vectorAt(4);

      // `e` + U+0301 + U+1F600 is 7 UTF-8 bytes, 4 UTF-16 code units and 3 code points. The
      // pinned prefix is `00000007`, so only the byte count can have produced it.
      expect(multiByte.idempotencyKey.length).toBe(4);
      expect([...multiByte.idempotencyKey].length).toBe(3);
      expect(Buffer.from(multiByte.idempotencyKey, 'utf8').length).toBe(7);
      expect(multiByte.preimage.endsWith('0000000765cc81f09f9880')).toBe(true);
    });

    it('is NOT equivalent to delimiter or plain concatenation', () => {
      const a = vectorAt(2);
      const b = vectorAt(3);

      // Both scopes flatten to `abcde`, so plain concatenation — and any single-delimiter scheme
      // over a domain that admits every printable ASCII character — would give one lock to two
      // different callers. Length prefixing gives two.
      expect(a.practiceId + a.userId + a.endpoint + a.idempotencyKey).toBe(
        b.practiceId + b.userId + b.endpoint + b.idempotencyKey,
      );
      expect(advisoryLockKey(scopeOf(a))).not.toBe(advisoryLockKey(scopeOf(b)));
    });

    it('reads the FIRST eight digest bytes, big-endian and SIGNED', () => {
      for (const vector of VECTORS) {
        const firstEight = vector.digest.slice(0, ADVISORY_LOCK_KEY_BYTES * 2);

        // Reconstructed from the PINNED digest hex by an independent route — `BigInt.asIntN` over
        // the unsigned big-endian reading — rather than by calling the function again.
        expect(advisoryLockKey(scopeOf(vector))).toBe(BigInt.asIntN(64, BigInt(`0x${firstEight}`)));
      }
    });

    it('yields keys inside the PostgreSQL signed bigint domain, sign included', () => {
      const keys = VECTORS.map((vector) => advisoryLockKey(scopeOf(vector)));

      expect(keys.some((key) => key < 0n)).toBe(true);
      expect(keys.some((key) => key > 0n)).toBe(true);

      for (const key of keys) {
        expect(key).toBeGreaterThanOrEqual(-(2n ** 63n));
        expect(key).toBeLessThanOrEqual(2n ** 63n - 1n);
      }
    });
  });

  describe('every scope component changes the lock', () => {
    it('gives four different keys for four single-component changes', () => {
      const base = scopeOf(vectorAt(0));

      const keys = new Set([
        advisoryLockKey(base),
        advisoryLockKey({ ...base, practiceId: '11111111-1111-4111-8111-111111111002' }),
        advisoryLockKey({ ...base, userId: '22222222-2222-4222-8222-222222222002' }),
        advisoryLockKey({ ...base, idempotencyKey: 'p5i4c-key-1x' }),
      ]);

      // Four distinct scopes, four distinct locks. A derivation that dropped a component would
      // collapse two of them.
      expect(keys.size).toBe(4);
    });
  });
});
